"""New baseline

Revision ID: 02000c410b26
Revises: 
Create Date: 2025-09-19 14:40:16.114555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from dotenv import load_dotenv
load_dotenv()

# revision identifiers, used by Alembic.
revision: str = '02000c410b26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
