"""Fixed user token data type

Revision ID: 0f683f6bda42
Revises: 02000c410b26
Create Date: 2025-10-07 22:29:52.258694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from dotenv import load_dotenv
load_dotenv()

# revision identifiers, used by Alembic.
revision: str = '0f683f6bda42'
down_revision: Union[str, Sequence[str], None] = '02000c410b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'token',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
