"""add contact source

Revision ID: 17cfbfcf2edf
Revises: 3ee1f4091b38
Create Date: 2025-12-13 18:02:27.789698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from dotenv import load_dotenv
load_dotenv()

# revision identifiers, used by Alembic.
revision: str = '17cfbfcf2edf'
down_revision: Union[str, Sequence[str], None] = '3ee1f4091b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('source', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'source')
    # ### end Alembic commands ###
