"""add child age

Revision ID: 3ee1f4091b38
Revises: 97911cdcc7ec
Create Date: 2025-12-13 17:35:02.037040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from dotenv import load_dotenv
load_dotenv()

# revision identifiers, used by Alembic.
revision: str = '3ee1f4091b38'
down_revision: Union[str, Sequence[str], None] = '97911cdcc7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('child_age', sa.Integer(), nullable=False))
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('contacts', 'child_age')
    # ### end Alembic commands ###
